apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermesmanager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hermesmanager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.adminPassword }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.slack.enabled .Values.slack.token }}
  slack-token: {{ .Values.slack.token | b64enc | quote }}
  {{- end }}
