apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hermesmanager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hermesmanager.labels" . | nindent 4 }}
