apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermesmanager.fullname" . }}-skills
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hermesmanager.labels" . | nindent 4 }}
data:
  hello-skill.yaml: |
    {{- .Values.skills | nindent 4 }}
